use `AllTeam`;

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'Person.unl' 
INTO TABLE Person
FIELDS TERMINATED BY '|' ;

LOAD DATA LOCAL INFILE 'Nurse.unl' 
INTO TABLE Nurse
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'MedicalCondition.unl' 
INTO TABLE MedicalCondition
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'Diagnosis.unl' 
INTO TABLE Diagnosis
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'Medication.unl' 
INTO TABLE Medication
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'Prescription.unl' 
INTO TABLE Prescription
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'Doctor.unl' 
INTO TABLE Doctor
FIELDS TERMINATED BY '|';

LOAD DATA LOCAL INFILE 'Appointment.unl' 
INTO TABLE Appointment
FIELDS TERMINATED BY '|';


SET FOREIGN_KEY_CHECKS = 1;
